### PR TITLE
Added Doggy Talents Support!

### PR DESCRIPTION
**Pull request by NovaViper**
I updated the textures from this [texturepack](https://minecraft.curseforge.com/projects/faithful-32x32-for-doggy-talents) to work with 1.12+

### CODE REVIEW

**Comment by magneticflux-** [comment]
Quick tip: you can write `Closes #9` to the body of your PR to let GitHub know that this pull request will solve a specific issue.

In addition, did you get permission from the author of those textures? It appears that their GitHub account is @fewizz and that they are a member of the F32Organization, but those textures are not licensed and so they default to "All rights reserved".

**Comment by fewizz** [comment]
i don't mind

**Comment by NovaViper** [comment]
Hey @fewizz, the developer of Doggy Talents started adding in lots of changes to the mod, so now we need many new textures ._.

**Comment by xMrVizzy** [comment]
thx, but not now, i'm curently working on Pocket Faithful, I think Faithful Mods will die, maybe i merge this project with F32Organization ang get acess to upload their texture on Curse or I don't know, realy I dont enough time to make all textures in Faithful, Pocket Faithful and I'm curently start modding.

**Comment by MarikCZ** [comment]
Hi @xMrVizzy


Maybe I have **solution**.

_You don't have time and you think that merging to **F32 organization** is only the one way.
Few months ago I started **project** on **Curse** - **Modded Faithful**, because your **Faithful Mods** was really **massive** project, and actually didn't work as I need. **Modded Faithful** contained only **few** mods, but had **all** textures of its mods and for **missing** textures I had **list.** However, I **canceled** it, because it was not complying with your **conditions** of resourcepack with similar (in my case **same**) content._

I had no more **time**, but I was trying to **contribute** to your project as **many** textures as I could, until I could. Now I have really **more** time, that I can spend to my **hobbies** - and drawing textures is one of them.

I don't understand your **system** of your work, but I know **basics** of drawing that you send me and I'll **keep** them.

Easiest way, is adding to me and other bigger **contributors** **permission** to this **GitHub** page and to upload files on **project site** of **Faithful Mods**. In short, make it more **public** and **Open-source**, because (in fact of your time) this **massive** project you can't develop **alone**.
I will wait for your **requirements** and ideas and I hope that we will find better **solution** for this project **existence**.


Have a nice day a **thanks** for your patience!

MarkShy (MarikCZ)

**Comment by MarikCZ** [comment]
Hi @xMrVizzy

Maybe I have **solution**.

You don't have time and you think that merging to **_F32 organization_** is only the one way.
Few months ago I started **project** on Curse - **_Modded Faithful_**, because your **_Faithful Mods_** are really **massive** project, and actually don't work as I need. Modded Faithful contained only **few** mods, but had all textures of its mods without **version mismatches**. However, I **canceled** it, because it was not complying with your **conditions** of resource-pack with similar (in my case same) content.
I had no more time, but I was trying to **contribute** to your project as **many** textures as I could, until I could. Now I have really more time, that I can spend to my **hobbies** - and drawing textures **is** one of them.

_**I am so sorry, if next text sounds offensive - I do not mean it wrong and I don't blame you - I understand your time lack.**_

I **want** help you, but I can't - _I haven't **permissions** to project site (which I understand a little)_, however I haven't even lowest level **permissions** to this GitHub **repository**. I spend much **time** to making **order** in textures (today TiC), but all is practically **useless**, _because can't upload it to my project (which I can't create because I I haven't permissions_), I can't  upload it there on **GitHub** - because I haven't **permissions** (to create branches, forks or pull requests), _I can't upload it on project site neither - because I haven't permissions._
I will wait for your **requirements** and ideas and I hope that we will find better **solution** for this project **existence**.

Have a **nice** day a thanks for your patience!

MarkShy (MarikCZ)

**Comment by xMrVizzy** [comment]
Okay, i will solve this mistake

**Comment by MarikCZ** [comment]
I am really looking-forward!

**Pull request closed without merging**
