### PR TITLE
Update pack.mcmeta

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
Updated pack.mcmeta.

### CODE REVIEW

**Comment by EltrutLikes** [comment]
I would recommend also changing "mod" in "includes mod textures" to "modded" and changing "Author:" to "Authors:".

**Comment by Johnmacrocraft** [comment]
@EltrutLikes Okay, gonna make commit as soon as possible.

**Comment by Johnmacrocraft** [comment]
@xMrVizzy @EltrutLikes Closing myself as mine and ElturtLikes' pull request was also closed. Gonna let xMrVizzy to do this.

**Comment by xMrVizzy** [comment]
Yea guys I already fix this in local repository on computer

**Pull request closed without merging**
